export const actionString = {
    SHOW_ITEM : 'SHOW',
    ADD : 'ADD',
    DELETE : 'DELETE',
    EDIT : 'EDIT',
    FILTER : 'FILTER'
}

export const actionStringService = {
    SHOW_ITEM : 'SHOW_SERVICE',
    ADD : 'ADD_SERVICE',
    DELETE : 'DELETE_SERVICE',
    EDIT : 'EDIT_SERVICE',
    FILTER : 'FILTER_SERVICE'
}

export const actionServerNote = {
    INITIAL_FETCH:'INITIALIZE_SERVER_NOTES',
    FETCH_COMPLETE:'SERVER_NOTES_FETCH_COMPLETE',
    FETCH_DATA : 'FETCH_SERVER_NOTES',
    SHOWN : 'SERVER_NOTES_SHOWN'
}

export const actionMailNote = {
    INITIAL_FETCH:'INITIALIZE_MAIL_NOTES',
    FETCH_COMPLETE:'MAIL_NOTES_FETCH_COMPLETE',
    FETCH_DATA : 'FETCH_MAIL_NOTES',
    SHOWN : 'MAIL_NOTES_SHOWN'
}

export const actionTaskNote = {
    INITIAL_FETCH:'INITIALIZE_TASK_NOTES',
    FETCH_COMPLETE:'TASK_NOTES_FETCH_COMPLETE',
    FETCH_DATA : 'FETCH_TASK_NOTES',
    SHOWN : 'TASK_NOTES_SHOWN'
}

export const actionDashboard = {
    INITIAL_FETCH : 'INITIALIZE_DASHBOARD',
    FETCH_COMPLETE:'INIT_FETCH_COMPLETE',
}

export const loginStrings = {
    LOGIN_ATTEMPT:'LOGIN_ATTEMPT',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_ERROR:'LOGIN_ERROR',
    LOGOUT:'LOGOUT'
}